apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: consumer-service
  template:
    metadata:
      labels:
        run: consumer-service
    spec:
      containers:
      - name: consumer-service
        image:  yugansethu/consumerkloud4:v1
        ports:
        - containerPort: 8081
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    run: consumer-service
spec:
  ports:
  - port: 8081
    protocol: TCP
  type: LoadBalancer
  selector:
    run: consumer-service