apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: producer-service
  template:
    metadata:
      labels:
        run: producer-service
    spec:
      containers:
      - name: producer-service
        image: yugansethu/consumerkloud:v1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    run: producer-service
spec:
  ports:
  - port: 8082
    protocol: TCP
  type: ClusterIP
  selector:
    run: producer-service